version: "3"


services:

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - ${HOST_PORT}:5432
    volumes:
      - postgres-pgdata:${PGDATA}
      - ${HOST_DB_INIT_SCRIPTS}:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_USER: ${postgres}
      POSTGRES_PASSWORD: ${2508}
      POSTGRES_DB: ${fitnes}
      PGDATA: ${public}


  server:
    build: server/

    command: python ./app.py

    ports:
      - 1234:1234



    depends_on:
      - server